import { Serie } from "./serie.js";
export var series = [
    new Serie("Stranger Things", 2016, 3, "The Duffer Brothers", ["Winona Ryder", "David Harbour", "Finn Wolfhard"], "Netflix", "Streaming", "https://www.netflix.com/title/80057281", "When a young boy disappears, his mother, a police chief, and his friends must confront terrifying supernatural forces in order to get him back.", "./images/Stranger_Things_S1V1.png"),
    new Serie("Breaking Bad", 2008, 5, "Vince Gilligan", ["Bryan Cranston", "Aaron Paul", "Anna Gunn"], "AMC", "Streaming", "https://ce.amc.com/series/breaking-bad", "A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine in order to secure his family's future.", "./images/BreakingBadS2DVD.jpg"),
    new Serie("Game of Thrones", 2011, 8, "David Benioff, D. B. Weiss", ["Emilia Clarke", "Kit Harington", "Peter Dinklage"], "HBO", "Streaming", "https://www.hbo.com/game-of-thrones", "Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for millennia.", "./images/GOT.jpg"),
    new Serie("The Office", 2005, 9, "Greg Daniels", ["Steve Carell", "Rainn Wilson", "John Krasinski"], "NBC", "Streaming", "https://www.nbc.com/the-office", "A mockumentary on a group of typical office workers, where the workday consists of ego clashes, inappropriate behavior, and tedium.", "./images/theOffice.jpg"),
    new Serie("Friends", 1994, 10, "David Crane, Marta Kauffman", ["Jennifer Aniston", "Courteney Cox", "Lisa Kudrow"], "NBC", "Streaming", "https://www.nbc.com/friends", "Follows the personal and professional lives of six twenty to thirty-something-year-old friends living in Manhattan.", "./images/friends.jpg"),
    new Serie("The Crown", 2016, 4, "Peter Morgan", ["Olivia Colman", "Tobias Menzies", "Helena Bonham Carter"], "Netflix", "Streaming", "https://www.netflix.com/title/80025678", "Follows the political rivalries and romance of Queen Elizabeth II's reign and the events that shaped the second half of the twentieth century.", "./images/theCrown.jpg")
];
